# Generated by Django 6.0.6 on 2026-06-04 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this approval template', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of when this template should be used')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is currently active')),
                ('auto_start_approval', models.BooleanField(default=True, help_text='Automatically start approval process when object is created')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ManyToManyField(help_text='Which model types this template applies to', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_approval_templates', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_approval_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval Template',
                'verbose_name_plural': 'Approval Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Order of this step (1-based, lower numbers first)')),
                ('title', models.CharField(blank=True, help_text='Human-readable title for this step', max_length=150)),
                ('can_edit', models.BooleanField(default=False, help_text='Whether approver can edit the object during approval')),
                ('allow_comments', models.BooleanField(default=False, help_text='Whether approver can add comments')),
                ('auto_approve', models.BooleanField(default=False, help_text='If enabled, this step is auto-approved without user action')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver_group', models.ForeignKey(blank=True, help_text='Group whose members can approve this step', null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('approver_user', models.ForeignKey(blank=True, help_text='Specific user who can approve this step', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(help_text='The template this step belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='django_4eyes.approvaltemplate')),
            ],
            options={
                'verbose_name': 'Approval Step',
                'verbose_name_plural': 'Approval Steps',
                'ordering': ['template', 'order'],
                'unique_together': {('template', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField(help_text='ID of the object being approved')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether the object has been fully approved')),
                ('is_rejected', models.BooleanField(default=False, help_text='Whether the object has been rejected')),
                ('actions_history', models.JSONField(blank=True, default=list, help_text='History of all actions taken during approval')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(help_text='Type of the object being approved', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_approval_states', to=settings.AUTH_USER_MODEL)),
                ('current_step', models.ForeignKey(blank=True, help_text='Current step in the approval process', null=True, on_delete=django.db.models.deletion.PROTECT, to='django_4eyes.approvalstep')),
                ('template', models.ForeignKey(help_text='The approval template being used', on_delete=django.db.models.deletion.CASCADE, to='django_4eyes.approvaltemplate')),
            ],
            options={
                'verbose_name': 'Approval State',
                'verbose_name_plural': 'Approval States',
                'ordering': ['-created_at'],
                'unique_together': {('content_type', 'object_id', 'template')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('approval_required', 'Approval Required'), ('approval_action', 'Approval Action Taken'), ('approval_completed', 'Approval Completed'), ('changes_requested', 'Changes Requested'), ('system', 'System Notification')], help_text='Type of notification', max_length=20)),
                ('title', models.CharField(help_text='Notification title', max_length=255)),
                ('message', models.TextField(blank=True, help_text='Notification message content')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the recipient has read this notification')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True)),
                ('acted', models.BooleanField(default=False, help_text='Whether the recipient has acted on this notification')),
                ('action_taken', models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('commented', 'Commented'), ('changes_requested', 'Changes Requested')], help_text='Action taken by the recipient', max_length=20)),
                ('object_id', models.CharField(blank=True, help_text='ID of the related object', max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of the related object', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, help_text='User who should receive this notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_notifications', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(blank=True, help_text='Approval step this notification is for', null=True, on_delete=django.db.models.deletion.CASCADE, to='django_4eyes.approvalstep')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='django_4eye_recipie_579cf7_idx'), models.Index(fields=['recipient', 'acted'], name='django_4eye_recipie_e8b166_idx'), models.Index(fields=['content_type', 'object_id'], name='django_4eye_content_a004a7_idx')],
            },
        ),
    ]
